name: Build CS3

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant permission
        run: chmod +x gradlew || true

      - name: Build plugin
        run: ./gradlew makePlugin

      - name: Upload cs3
        uses: actions/upload-artifact@v4
        with:
          name: cs3
          path: build/plugins/*.cs3
